title: Nguyen Thuy Trinh
logo: /assets/images/avatar.png
description: I am a dedicated data analyst constantly working to enhance my skills and knowledge. With expertise in advanced analytical tools and techniques, I am committed to providing valuable insights, reports, and strategic recommendations. I maintain a professional and collaborative mindset across the organization and focus on continuous learning.
show_downloads: true
theme: jekyll-theme-minimal
