title: Nguyen Thuy Trinh
logo: /assets/images/avatar.png
description: Data is not just numbers – it’s a hidden story waiting for the analyst to uncover and convey.
show_downloads: true
theme: jekyll-theme-minimal
